server:
  port: 8081

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitnessdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    rabbit:
      enabled: false

rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: activity.exchange
  routing:
    key: activity.routing.key