server:
  port: 8081
spring:
    application:
        name: userService
    datasource:
        url: jdbc:postgresql://localhost:5432/fitness_user_db
        username: postgres
        password: 1706

    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect


